src/java/ManagedBeans/QuestionJSFManagedBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManagedBeans;

import entities.Question;
import entities.Reponse;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.ejb.EJB;
import modele.QuestionFacade;
import modele.ReponseFacade;

@Named(value = "questionJSFManagedBean")
@SessionScoped
public class QuestionJSFManagedBean implements Serializable {

    @EJB
    private ReponseFacade reponseFacade;

    @EJB
    private QuestionFacade questionFacade;
    
    private int idExam;
    private List<Question> questions;
    private List<List<Reponse>> reponses;
    private int idDesQuestions = -1;
    private int notedeBareme = 0;
    private int note = 0;
    private String[][] selectedRep ;

    public int getnote() {
        return note;
    }
     public QuestionJSFManagedBean() {
    }Z
    public void setnote(int note) {
        this.note = note;
    }

    public String affichernote(){
        
        for(int i=0; i<selectedRep.length; i++)
            note += selectedRep[i].length;
        return "notejsf?note=" + note;
    }
    
    public String[][] getSelectedRep() {
        return selectedRep;
    }

    public void setSelectedRep(String[][]selectedRep) {
        this.selectedRep = selectedRep;
    }
    
    
    public int getnotedeBareme() {
        return notedeBareme;
    }

    public void setnotedeBareme(int note) {
        this.notedeBareme = note;
    }
    
    
    public int getidDesQuestions() {
        return idDesQuestions;
    }

    public void setidDesQuestions(int idDesQuestions) {
        this.idDesQuestions = idDesQuestions;
    }
    
    
    public int getIdExam() {
        return idExam;
    }

    public void setIdExam(int idExam) {
        this.idExam = idExam;
    }
    
    public List<Question> getQuestions() {
        return questions;
    }

    public void setQuestions(List<Question> questions) {
        this.questions = questions;
    }
     public String[] getSelReponses() {
         idDesQuestions = (idDesQuestions + 1)%questions.size();
        return selectedRep[idDesQuestions];
    }
     
    public List<Reponse> getReponses() {
       idDesQuestions = (idDesQuestions + 1)%questions.size();
        return reponses.get(idDesQuestions);
    }

    public void setReponses(List<List<Reponse>> reponses) {
        this.reponses = reponses;
        
    }
    
    public void findQuestions(){
        idDesQuestions = -1;
        notedeBareme = 0;
        note = 0;
        questions = questionFacade.findByEx(idExam);
        selectedRep = new String[questions.size()][4];
    }
    
    public void findReponses(){
        reponses = reponseFacade.findByQuestions(questions);
        for(int i=0; i< reponses.size(); i++){
            for(int j=0; j<reponses.get(i).size(); j++){
                notedeBareme += reponses.get(i).get(j).getIsGood();
            }
        }
    }
    
    public String PasserExam(int idExam){
        return "Examjsf?idExam=" + idExam;
    }
    
   
    
}

web/Examjsf.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
     <f:metadata>
         <f:viewParam  name="idExam" value="#{questionJSFManagedBean.idExam}" required="true" />
         <f:viewAction action="#{questionJSFManagedBean.findQuestions}"/>
         <f:viewAction action="#{questionJSFManagedBean.findReponses}"/>
    </f:metadata>
    <h:body>
        
        <f:view>
            <h:outputText value="Le score total de cet exam est: "/>
            <h:outputText value="#{questionJSFManagedBean.barem}"/>

            <h:form>
                <h1><h:outputText value="List"/></h1>
                <p:dataTable value="#{questionJSFManagedBean.questions}" var="item">
                   
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Question"/>
                        </f:facet>
                        <h:outputText value="#{item.question}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Consigne"/>
                        </f:facet>
                        <h:outputText value="#{item.consigne}"/>
                    </p:column>
                    <p:column>
                        <h:selectManyCheckbox  value="#{questionJSFManagedBean.selReponses}" layout="pageDirection">               
                            <f:selectItems value="#{questionJSFManagedBean.reponses}" var="rep" itemLabel="#{rep.reponse}" itemValue="#{rep.idReponse}" />
                        </h:selectManyCheckbox>
                    </p:column>
                </p:dataTable>

                <h:commandButton value="valider exam " immediate="true" action="" />  
            </h:form>


        </f:view>

    </h:body>
</html>

web/ListExamsjsf.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <f:view>


            <h:form>
                <h1><h:outputText value="List"/></h1>
                <p:dataTable value="#{examsJSFManagedBean.findExams()}" var="item">
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Idexam"/>
                        </f:facet>
                        <h:link outcome="#{questionJSFManagedBean.PasserExam(item.idexam)}" value="#{item.idexam}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Creneau"/>
                        </f:facet>
                        <h:outputText value="#{item.creneau}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="IdCours"/>
                        </f:facet>
                        <h:outputText value="#{item.idCours}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Idgroupe"/>
                        </f:facet>
                        <h:outputText value="#{item.idgroupe}"/>
                    </p:column>
                    <p:column>
                        <f:facet name="header">
                            <h:outputText value="Qcm"/>
                        </f:facet>
                        <h:outputText value="#{item.qcm}"/>
                    </p:column>
                </p:dataTable>
            </h:form>

        </f:view>

    </h:body>
</html>